### ISSUE TITLE
Question: Calculate diff Mendoza Patch

### ISSUE THREAD

**Issue by kartikjain26** [sanity-io/mendoza#1]
I have two Json variables. I want to calculate diff between them and store their Mendoza patch in my database.

Is this supported by Mendoza library ? Kindly update the full documentation for Mendoza.

**Comment by judofyr** [comment]
Yes, this is possible by using Mendoza as a library. You can find the documentation at https://pkg.go.dev/github.com/sanity-io/mendoza.

You would use [CreatePatch](https://pkg.go.dev/github.com/sanity-io/mendoza#CreatePatch) to create a patch, and then [ApplyPatch](https://pkg.go.dev/github.com/sanity-io/mendoza#ApplyPatch) to apply the patch again.

**Comment by kartikjain26** [comment]
@judofyr Can this be imported in a javascript project ? From npm ?

**Comment by judofyr** [comment]
There's currently no way of _creating_ a patch in JavaScript. You can only apply it (by using [mendoza-js](https://github.com/sanity-io/mendoza-js)).

**Comment by kartikjain26** [comment]
Thanks for the update. Is this being worked upon ?

**Comment by judofyr** [comment]
No, there is no plans to extend the JavaScript library to also create patches unfortunately.
