### ISSUE TITLE
cmd/dozapatch

### ISSUE THREAD

**Issue by AiyionPrime** [sanity-io/mendoza#5]
This project is looking really nice; and quite likely I'm overlooking somthing here.
There's cmd/dozadiff; but not e.g. cmd/dozapatch, though the library-code appears to be in this repo.
It appears like it would be rather easy to implement it, so I just wanted to make sure it was not left out intentionally for some good reason?

It feels weird to need both go and node to complete the circle on commandline. 
Does dozapatch exist and I just didn't see it?

**Comment by AiyionPrime** [comment]
At the bottom of the readme:
> The patch can only be applied against the exact same version.

The version of the node project is available, but this project seems to lack one?
Possibly the git tags were not pushed yet.

**Comment by judofyr** [comment]
There's no particular reason why `dozapatch` wasn't added. We're mainly using this as a library and don't actually use the `dozadiff` utility in practice. I'm opened a PR for adding `dozapatch` as well. Does this work for you?

**Comment by AiyionPrime** [comment]
I'll give it a try, one moment please.

**Comment by AiyionPrime** [comment]
This looks very good, thanks!
```
/tmp/mendoza$ dozadiff left.json right.json 
[19,1,10,1,14,"firstName",11,2,20,"Diffing",21,0,2,15]
/tmp/mendoza$ dozadiff left.json right.json > patch.json
/tmp/mendoza$ dozapatch left.json patch.json 
{"age":30,"firstName":"Bob Bobson","skills":["Diffing","Go","Patching"]}
/tmp/mendoza$ dozapatch left.json patch.json > right2.json
/tmp/mendoza$ dozadiff right.json right2.json 
[]
```

Any input on the version of mendoza?

**Comment by judofyr** [comment]
Mendoza-the-library or Mendoza-the-format?

Mendoza-the-format is very much stable and won't change in any foreseeable future. I'm unsure about this library. We just pin to a specific commit in `go.mod`, but I guess I can tag some arbitrary number if that helps you.

**Comment by AiyionPrime** [comment]
After reading the article about mendoza, I came to the conclusion, it was important to have the patcher and the differ for the same version.
Apparently the format does not change as often as I thought was implied, but yes, my question was about which version of the format this library supports.

I thought about packaging this for the arch user repository; in case you would find any arbitrary version tags for this library as well, it would be a great help.

**Comment by judofyr** [comment]
> After reading the article about mendoza, I came to the conclusion, it was important to have the patcher and the differ for the same version.

Yes, that's correct. Potentially in the future we may want to add further operations, however so far, we haven't really seen the need to expand the operation set. I think that long-term this library will always maintain backwards-compatibility.

What about tagging the current version as `v1.0.0` and then we bump the minor when the format is expanded and teeny for other changes?

**Comment by AiyionPrime** [comment]
Sounds good.
