### ISSUE TITLE
Diff/patch may produce non-identical JSON

### ISSUE THREAD

**Issue by djherbis** [sanity-io/mendoza#8]
Is it expected that the reversing a diff/patch may produce non-binary equivalent JSON?

ex.
```
dozadiff a b > diff
dozapatch a diff > b2
dozadiff b b2 # [] empty
diff b b2 # non-empty
```

The file in question is quite large, it appears like it is effectively the same, but not exactly the same.

Does this affect composition of patches?
```
dozadiff a b > abdiff
dozadiff b c > bcdiff
dozapatch a abdiff > b2
dozapatch b2 bcdiff > c2
dozadiff c c2 # [] empty
diff c c2 # non-empty
```

Can this potentially cause problems, or as long as dozadiff thinks there is no diff then the patch should still work?

**Comment by judofyr** [comment]
The tools `dozadiff` and `dozapatch` will not normalize the patch nor the outputted JSON. They should be semantically equivalent though. E.g. `a` could be`{"name":"Bob","karma":100}` and `b` could be `{"karma":100,"name":"Bob"}`. As long as `dozadiff` returns an empty array then all should be good.
